Repository DataKrewTech/MADS-IoT-Explorer, pull requests merged in 2020-04, with the labels that each got.

#18 Feature/timescale integration
  .github/workflows/elixir.yml
  apps/acqdat_core/lib/acqdat_core/model/gateway_data.ex
  apps/acqdat_core/lib/acqdat_core/model/sensor_data.ex
  apps/acqdat_core/lib/acqdat_core/schema/gateway.ex
  apps/acqdat_core/lib/acqdat_core/schema/gateway_data.ex
  apps/acqdat_core/lib/acqdat_core/schema/sensors_data.ex
  apps/acqdat_core/priv/repo/migrations/20200413084047_enable_timescale_extensions.exs
  apps/acqdat_core/priv/repo/migrations/20200413175306_create_sensor_data_table.exs
  apps/acqdat_core/priv/repo/migrations/20200414051417_create_gateway_data_table.exs
  apps/acqdat_core/test/schema/gateway_data_test.ex
  apps/acqdat_core/test/schema/sensor_data_test.exs
  apps/acqdat_core/test/support/factory/factory.ex
Labels: Review Changes Done, Review Done, feature

#26 Did proper scoping of routes as per the organisation_id
  apps/acqdat_api/lib/acqdat_api_web/router.ex
  apps/acqdat_api/test/acqdat_api_web/controllers/user_controller_test.ex
  apps/acqdat_api/test/acqdat_api_web/controllers/user_controller_test.exs
  apps/acqdat_api/test/acqdat_api_web/controllers/user_setting_controller_test.exs
  apps/acqdat_api/test/acqdat_api_web/controllers/user_widget_controller_test.exs
Labels: Ready for Review

#23 Elasticsearch/users
  apps/acqdat_api/lib/acqdat_api/elasticsearch.ex
  apps/acqdat_api/lib/acqdat_api/user.ex
  apps/acqdat_api/lib/acqdat_api/widgets/widget.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/organisation_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/role_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/user_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/widgets/user_widget_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/widgets/widget_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/plugs/load_org.ex
  apps/acqdat_api/lib/acqdat_api_web/plugs/load_user.ex
  apps/acqdat_api/lib/acqdat_api_web/router.ex
  apps/acqdat_api/lib/acqdat_api_web/validators/role.ex
  apps/acqdat_api/lib/acqdat_api_web/validators/widgets/widget.ex
  apps/acqdat_api/lib/acqdat_api_web/views/organisation_view.ex
  apps/acqdat_api/lib/acqdat_api_web/views/role_view.ex
  apps/acqdat_api/lib/acqdat_api_web/views/user_setting_view.ex
  apps/acqdat_api/lib/acqdat_api_web/views/user_view.ex
  apps/acqdat_api/lib/acqdat_api_web/views/widgets/user_widget_view.ex
  apps/acqdat_api/lib/acqdat_api_web/views/widgets/widget_view.ex
  apps/acqdat_api/mix.exs
  apps/acqdat_api/test/acqdat_api_web/controllers/auth_controller_test.exs
  apps/acqdat_api/test/acqdat_api_web/controllers/organisation_controller_test.exs
  apps/acqdat_api/test/acqdat_api_web/controllers/user_controller_test.exs
  apps/acqdat_api/test/acqdat_api_web/controllers/user_setting_controller_test.exs
  apps/acqdat_api/test/acqdat_api_web/controllers/user_widget_controller_test.exs
  apps/acqdat_api/test/acqdat_api_web/controllers/widget_controller_test.exs
  apps/acqdat_core/lib/acqdat_core/model/role.ex
  apps/acqdat_core/lib/acqdat_core/model/user.ex
  apps/acqdat_core/lib/acqdat_core/schema/role.ex
  apps/acqdat_core/lib/acqdat_core/schema/user.ex
  apps/acqdat_core/lib/acqdat_core/widgets/schema/widget.ex
  apps/acqdat_core/mix.exs
  apps/acqdat_core/priv/repo/migrations/20200415050023_acqdat_roles.exs
  apps/acqdat_core/priv/repo/migrations/20200416093507_alter_users_table.exs
  apps/acqdat_core/priv/repo/seed/role.ex
  apps/acqdat_core/priv/repo/seed/user.ex
  apps/acqdat_core/priv/repo/seed/widget.ex
  apps/acqdat_core/priv/repo/seeds.exs
  apps/acqdat_core/test/domain/account_test.exs
  apps/acqdat_core/test/schema/role.exs
  apps/acqdat_core/test/schema/user_test.exs
  apps/acqdat_core/test/support/factory/factory.ex
  config/dev.exs
  mix.exs
  mix.lock
Labels: Ready for Review, feature

#21 Feature/user associations
  apps/acqdat_api/lib/acqdat_api/user.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/user_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/widgets/user_widget_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/router.ex
  apps/acqdat_api/lib/acqdat_api_web/validators/user.ex
  apps/acqdat_api/lib/acqdat_api_web/views/user_view.ex
  apps/acqdat_api/test/acqdat_api_web/controllers/auth_controller_test.exs
  apps/acqdat_api/test/acqdat_api_web/controllers/user_controller_test.exs
  apps/acqdat_core/lib/acqdat_core/model/user.ex
  apps/acqdat_core/lib/acqdat_core/schema/app.ex
  apps/acqdat_core/lib/acqdat_core/schema/asset.ex
  apps/acqdat_core/lib/acqdat_core/schema/user.ex
  apps/acqdat_core/lib/acqdat_core/schema/user_app.ex
  apps/acqdat_core/lib/acqdat_core/schema/user_asset.ex
  apps/acqdat_core/priv/repo/migrations/20200415062008_add_table_asset_user.exs
  apps/acqdat_core/priv/repo/migrations/20200415100427_add_table_apps.exs
  apps/acqdat_core/priv/repo/migrations/20200415102453_add_table_app_user.exs
  apps/acqdat_core/test/domain/account_test.exs
  apps/acqdat_core/test/model/user_test.exs
  apps/acqdat_core/test/schema/user_app_test.exs
  apps/acqdat_core/test/schema/user_asset_test.exs
  apps/acqdat_core/test/schema/user_test.exs
  apps/acqdat_core/test/support/factory/factory.ex
Labels: Ready for Review, Review Changes Done, feature

#20 Feature/user invitations
  apps/acqdat_api/lib/acqdat_api/invitation.ex
  apps/acqdat_api/lib/acqdat_api/user.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/invitation_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/user_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/plugs/cors.ex
  apps/acqdat_api/lib/acqdat_api_web/res_messages.ex
  apps/acqdat_api/lib/acqdat_api_web/router.ex
  apps/acqdat_api/lib/acqdat_api_web/validators/invitation.ex
  apps/acqdat_api/lib/acqdat_api_web/validators/user.ex
  apps/acqdat_api/lib/acqdat_api_web/views/invitation_view.ex
  apps/acqdat_api/lib/acqdat_api_web/views/user_view.ex
  apps/acqdat_api/test/acqdat_api_web/controllers/invitation_controller_test.exs
  apps/acqdat_api/test/acqdat_api_web/controllers/user_controller_test.exs
  apps/acqdat_core/lib/acqdat_core/mailer/templates/email/user_invitation_email.html.eex
  apps/acqdat_core/lib/acqdat_core/mailer/user_invitation_email.ex
  apps/acqdat_core/lib/acqdat_core/model/Invitation.ex
  apps/acqdat_core/lib/acqdat_core/schema/invitation.ex
  apps/acqdat_core/lib/acqdat_core/schema/user.ex
  apps/acqdat_core/priv/repo/migrations/20200416102925_create_table_invitations.exs
  apps/acqdat_core/test/mailer/user_invitation_email_test.exs
  apps/acqdat_core/test/model/invitation_test.exs
  apps/acqdat_core/test/schema/invitation.ex
  apps/acqdat_core/test/support/factory/factory.ex
  env/example.env
Labels: Making Changes, feature

#29 Feature/teams associations
  apps/acqdat_api/lib/acqdat_api/team.ex
  apps/acqdat_api/lib/acqdat_api/user.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/team_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/user_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/plugs/load_current_user.ex
  apps/acqdat_api/lib/acqdat_api_web/plugs/load_team.ex
  apps/acqdat_api/lib/acqdat_api_web/router.ex
  apps/acqdat_api/lib/acqdat_api_web/validators/team.ex
  apps/acqdat_api/lib/acqdat_api_web/views/team_view.ex
  apps/acqdat_api/lib/acqdat_api_web/views/user_view.ex
  apps/acqdat_api/test/acqdat_api_web/controllers/team_controller_test.exs
  apps/acqdat_api/test/acqdat_api_web/controllers/user_controller_test.exs
  apps/acqdat_core/lib/acqdat_core/model/team.ex
  apps/acqdat_core/lib/acqdat_core/model/user.ex
  apps/acqdat_core/lib/acqdat_core/schema/app.ex
  apps/acqdat_core/lib/acqdat_core/schema/invitation.ex
  apps/acqdat_core/lib/acqdat_core/schema/org_app.ex
  apps/acqdat_core/lib/acqdat_core/schema/organisation.ex
  apps/acqdat_core/lib/acqdat_core/schema/team.ex
  apps/acqdat_core/lib/acqdat_core/schema/team_app.ex
  apps/acqdat_core/lib/acqdat_core/schema/team_asset.ex
  apps/acqdat_core/lib/acqdat_core/schema/user.ex
  apps/acqdat_core/lib/acqdat_core/schema/user_team.ex
  apps/acqdat_core/priv/repo/migrations/20200418143148_create_table_teams.exs
  apps/acqdat_core/priv/repo/migrations/20200418145154_create_table_user_team.exs
  apps/acqdat_core/priv/repo/migrations/20200418151320_create_table_teams_assets.exs
  apps/acqdat_core/priv/repo/migrations/20200418151700_create_table_teams_apps.exs
  apps/acqdat_core/priv/repo/migrations/20200424103647_alter_apps_table.exs
  apps/acqdat_core/priv/repo/migrations/20200424131558_create_table_app_org_apps.exs
  apps/acqdat_core/test/model/team_test.exs
  apps/acqdat_core/test/schema/team_app_test.exs
  apps/acqdat_core/test/schema/team_asset_test.exs
  apps/acqdat_core/test/schema/team_test.exs
  apps/acqdat_core/test/schema/user_team_test.exs
  apps/acqdat_core/test/support/factory/factory.ex
Labels: Ready for Review, Review Changes Done, feature
