Repository DataKrewTech/MADS-IoT-Explorer, pull requests merged in 2020-05, with the labels that each got.

#32 Enhancements/user avatar
  apps/acqdat_api/lib/acqdat_api/role-management/user.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/role-management/invitation_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/role-management/user_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/views/role-management/user_view.ex
  apps/acqdat_core/lib/acqdat_core/role-management/model/user.ex
  apps/acqdat_core/lib/acqdat_core/role-management/schema/user.ex
  apps/acqdat_core/priv/repo/migrations/20200430145438_add_avatar_column_to_users_table.exs
Labels: Ready for Review, Review Changes Done

#34 Feature/apps seed
  apps/acqdat_api/lib/acqdat_api_web/controllers/app_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/organisation_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/role-management/user_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/router.ex
  apps/acqdat_api/lib/acqdat_api_web/validators/app.ex
  apps/acqdat_api/lib/acqdat_api_web/views/app_view.ex
  apps/acqdat_api/lib/acqdat_api_web/views/organisation_view.ex
  apps/acqdat_api/test/acqdat_api_web/controllers/app_controller_test.exs
  apps/acqdat_core/lib/acqdat_core/model/organisation.ex
  apps/acqdat_core/lib/acqdat_core/role-management/model/app.ex
  apps/acqdat_core/lib/acqdat_core/role-management/schema/app.ex
  apps/acqdat_core/mix.exs
  apps/acqdat_core/priv/repo/mads_apps.csv
  apps/acqdat_core/priv/repo/migrations/20200505063225_add_icon_id_column_to_apps_table.exs
  apps/acqdat_core/priv/repo/seed/app.ex
  apps/acqdat_core/priv/repo/seeds.exs
  apps/acqdat_core/test/role-management/model/app_test.exs
  apps/acqdat_core/test/support/factory/factory.ex
Labels: Ready for Review

#44 [S10U1T1]Remove teams table and associations
  apps/acqdat_api/lib/acqdat_api/role-management/team.ex
  apps/acqdat_api/lib/acqdat_api/role-management/user.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/role-management/team_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/role-management/user_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/plugs/load_team.ex
  apps/acqdat_api/lib/acqdat_api_web/router.ex
  apps/acqdat_api/lib/acqdat_api_web/validators/role-management/team.ex
  apps/acqdat_api/lib/acqdat_api_web/views/role-management/team_view.ex
  apps/acqdat_api/lib/acqdat_api_web/views/role-management/user_view.ex
  apps/acqdat_api/test/acqdat_api_web/controllers/role-management/team_controller_test.exs
  apps/acqdat_core/lib/acqdat_core/role-management/model/team.ex
  apps/acqdat_core/lib/acqdat_core/role-management/model/user.ex
  apps/acqdat_core/lib/acqdat_core/role-management/schema/team.ex
  apps/acqdat_core/lib/acqdat_core/role-management/schema/team_app.ex
  apps/acqdat_core/lib/acqdat_core/role-management/schema/team_asset.ex
  apps/acqdat_core/lib/acqdat_core/role-management/schema/user.ex
  apps/acqdat_core/lib/acqdat_core/role-management/schema/user_team.ex
  apps/acqdat_core/priv/repo/migrations/20200519111338_remove_teams_table_and_its_associations.exs
  apps/acqdat_core/test/role-management/model/team_test.exs
  apps/acqdat_core/test/role-management/schema/team_app_test.exs
  apps/acqdat_core/test/role-management/schema/team_asset_test.exs
  apps/acqdat_core/test/role-management/schema/team_test.exs
  apps/acqdat_core/test/role-management/schema/user_team_test.exs
  apps/acqdat_core/test/support/factory/factory.ex
Labels: Ready for Review

#47 Add position update logic to assets model
  apps/acqdat_core/lib/acqdat_core/entity-management/model/asset.ex
  apps/acqdat_core/lib/acqdat_core/entity-management/schema/asset.ex
  apps/acqdat_core/test/entity-management/model/asset_test.exs
  mix.lock
Labels: Ready for Review, enhancement

#42 Feature/entities context
  .gitignore
  apps/acqdat_api/lib/acqdat_api/elasticsearch.ex
  apps/acqdat_api/lib/acqdat_api/entity-management/asset.ex
  apps/acqdat_api/lib/acqdat_api/entity-management/sensor_type.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/entity-management/asset_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/controllers/entity-management/sensor_type_controller.ex
  apps/acqdat_api/lib/acqdat_api_web/plugs/load_sensor_type.ex
  apps/acqdat_api/lib/acqdat_api_web/router.ex
  apps/acqdat_api/lib/acqdat_api_web/validators/entity-management/asset.ex
  apps/acqdat_api/lib/acqdat_api_web/validators/entity-management/sensor_type.ex
  apps/acqdat_api/lib/acqdat_api_web/views/entity-management/asset_view.ex
  apps/acqdat_api/lib/acqdat_api_web/views/entity-management/sensor_type_view.ex
  apps/acqdat_api/test/acqdat_api_web/controllers/entity-management/asset_controller_test.exs
  apps/acqdat_api/test/acqdat_api_web/controllers/entity-management/sensor_controller_test.exs
  apps/acqdat_api/test/acqdat_api_web/controllers/entity-management/sensor_type_controller_test.exs
  apps/acqdat_api/test/acqdat_api_web/controllers/role-management/user_controller_test.exs
  apps/acqdat_core/lib/acqdat_core/entity-management/model/asset.ex
  apps/acqdat_core/lib/acqdat_core/entity-management/model/sensor_type.ex
  apps/acqdat_core/lib/acqdat_core/entity-management/schema/asset.ex
  apps/acqdat_core/lib/acqdat_core/entity-management/schema/sensor.ex
  apps/acqdat_core/lib/acqdat_core/entity-management/schema/sensor_type.ex
  apps/acqdat_core/priv/repo/migrations/20200504072105_add_sensor_type.exs
  apps/acqdat_core/priv/repo/migrations/20200504074636_alter_sensor.exs
  apps/acqdat_core/priv/repo/migrations/20200511005409_alter_asset_table.exs
  apps/acqdat_core/priv/repo/migrations/20200525212037_alter_sensor_type.exs
  apps/acqdat_core/priv/repo/seed/entity-management/asset.ex
  apps/acqdat_core/priv/repo/seed/helpers/widget_helpers.ex
  apps/acqdat_core/priv/repo/seed/role-management/role.ex
  apps/acqdat_core/priv/repo/seed/widget.ex
  apps/acqdat_core/priv/repo/seed/widgets/area.ex
  apps/acqdat_core/priv/repo/seed/widgets/bar.ex
  apps/acqdat_core/priv/repo/seed/widgets/line.ex
  apps/acqdat_core/priv/repo/seed/widgets/pie.ex
  apps/acqdat_core/test/entity-management/model/asset_test.exs
  apps/acqdat_core/test/entity-management/model/sensor_test.exs
  apps/acqdat_core/test/entity-management/schema/asset_test.exs
  apps/acqdat_core/test/entity-management/schema/sensor_test.exs
  apps/acqdat_core/test/entity-management/schema/sensor_type_test.exs
  apps/acqdat_core/test/role-management/model/user_test.exs
  apps/acqdat_core/test/role-management/schema/user_asset_test.exs
  apps/acqdat_core/test/role-management/schema/user_test.exs
  apps/acqdat_core/test/support/factory/factory.ex
  apps/acqdat_core/test/support/factory/hierarchy.ex
  mix.lock
Labels: Ready for Review
